language: he
lang_direction: rtl
landing_page:
  welcome_message:
    text: '专  住 砖!'
  name_form:
    text: ' 砖 驻专  住住转 住?'
    name_placeholder_text: 砖 砖 
    password_placeholder_text: 住住 
    submit_button_text: 砖
navbar:
  title:
    text:  转 砖  コ
text_chat:
  submit_button_text: 砖
  placeholder_text: '注 砖 注专转 '

